// Floating action buttons, toast notifications and modals

        function openRewrite(kw){S.rewriteKeyword=kw;render();}
        function closeRewrite(){S.rewriteKeyword=null;render();}
        function copyText(t){navigator.clipboard?.writeText(t).catch(()=>{});showToast('Copied!');}
        function showToast(msg){S.toast=msg;render();setTimeout(()=>{S.toast=null;render();},2500);}
        function loadHistory(i){const h=S.history[i];if(h&&h.results){S.results=h.results;S.analysisDone=true;S.showDiff=false;navigate('dashboard');render();setTimeout(animateScore,300);}}
        function clearHistory(){S.history=[];localStorage.setItem('smp_history','[]');render();}

        function renderFloating(){if(!S.analysisDone)return '';return `<div class="no-print fixed bottom-6 right-6 flex flex-col gap-3 z-30"><button onclick="window.print()" aria-label="Export report as PDF" class="w-12 h-12 rounded-2xl glass flex items-center justify-center hover:scale-110 transition shadow-lg"><i class="fas fa-file-pdf text-purple-400"></i></button><button onclick="S.shareId=Math.random().toString(36).slice(2,8);localStorage.setItem('smp_share_'+S.shareId,JSON.stringify({score:S.results.matchScore}));S.shareModal=true;render();" aria-label="Share report" class="w-12 h-12 rounded-2xl glass flex items-center justify-center hover:scale-110 transition shadow-lg"><i class="fas fa-share-nodes text-cyan-400"></i></button></div>`;}
        function renderToast(){if(!S.toast)return '';return `<div role="status" aria-live="polite" class="fixed top-20 right-6 z-50 toast-in glass px-5 py-3 rounded-2xl flex items-center gap-3 shadow-2xl border border-green-500/20"><i class="fas fa-check-circle text-green-400"></i><span>${S.toast}</span></div>`;}
        function renderRewriteModal(){if(!S.rewriteKeyword||!REWRITES[S.rewriteKeyword])return '';const suggestions = REWRITES[S.rewriteKeyword];return `<div class="modal-overlay active" onclick="if(event.target===this)closeRewrite()" role="dialog" aria-modal="true" aria-labelledby="rewriteTitle"><div class="modal-body"><div class="flex justify-between"><h3 id="rewriteTitle" class="font-bold">Rewrite for "${S.rewriteKeyword}"</h3><button onclick="closeRewrite()" aria-label="Close dialog"><i class="fas fa-xmark"></i></button></div>${suggestions.map(s=>`<button onclick="copyText('${s}');closeRewrite()" class="w-full text-left p-3 rounded-xl bg-white/5 border border-white/10 text-sm hover:bg-white/10 mt-2">${s}</button>`).join('')}</div></div>`;}
        function renderShareModal(){if(!S.shareModal)return '';const link=`skillmatch.pro/share/${S.shareId}`;return `<div class="modal-overlay active" onclick="if(event.target===this){S.shareModal=false;render();}" role="dialog" aria-modal="true" aria-labelledby="shareTitle"><div class="modal-body"><div class="flex justify-between"><h3 id="shareTitle" class="font-bold"><i class="fas fa-share-nodes text-cyan-400 mr-2"></i>Share</h3><button onclick="S.shareModal=false;render();" aria-label="Close dialog"><i class="fas fa-xmark"></i></button></div><p class="text-sm text-muted">Anonymized link (score only).</p><div class="flex items-center gap-2 mt-4 p-3 rounded-xl bg-white/5"><code class="flex-1 text-sm truncate">${link}</code><button onclick="copyText('${link}')" class="px-3 py-1 rounded-lg bg-cyan-500/20 text-cyan-400 text-xs">Copy</button></div></div></div>`;}
